security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Toutes les routes API gèrent leur propre authentification via TokenGenerator
    api:
      pattern: ^/api
      stateless: true
      security: false

  access_control: []
